### ISSUE TITLE
Handle dynamic highlight fields

### ISSUE THREAD

**Issue by franvera** [knoxpo/dart_algolia#1]
Crashes when _highlightResult contains other field types.

Error is coming from `object_snapshot.dart` -> `AlgoliaObjectSnapshot.fromMap` when parsing `map._highlightResult`

Error: `type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>'`

**Comment by nhathiwala** [comment]
Resolved in ``0.1.3+2`` updated.
 Thank you
