### ISSUE TITLE
Multiples queries search

### ISSUE THREAD

**Issue by olamarche** [knoxpo/dart_algolia#13]
**Is your feature request related to a problem? Please describe.**
No problem related, nice package!
**Describe the solution you'd like**
Implement the multiples indexes search supported by Algolia
**Describe alternatives you've considered**
I have to search in 3 differents indices, I would likes to not invoke 3 difference search request in order to get my result :).
**Additional context**
Additional info :
https://www.algolia.com/doc/api-reference/api-methods/multiple-queries/?language=javascript

**Comment by Mikkelet** [comment]
I would LOVE this too <3

**Comment by nhathiwala** [comment]
Hi @olamarche & @Mikkelet, 

Thank you all for selecting dart_algolia package for your Dart projects and supporting the development. 

Multiple queries are in our pipeline of our TODOS, we should be rolling-out that functionality by the end of this May. 

Till then you can use an alternative method, I know it's not that efficient as Multiple queries, but just a workaround:
 ```dart
    AlgoliaQuery queryA = algolia.instance.index('indiceA').search('john');
    AlgoliaQuery queryB = algolia.instance.index('indiceB').search('john');

    // Perform multiple facetFilters
    queryA = queryA.setFacetFilter('status:published');
    queryA = queryA.setFacetFilter('isDelete:false');

    // Perform multiple facetFilters
    queryB = queryB.setFacetFilter('status:published');
    queryB = queryB.setFacetFilter('isDelete:false');

    // Get Result
    List<AlgoliaQuerySnapshot> snap = await Future.wait([queryA.getObjects(), queryB.getObjects()]);
```

🍻

**Comment by olamarche** [comment]
@nhathiwala Thank you for the fix
I'm look forward for the next release!

**Comment by Mikkelet** [comment]
> Hi @olamarche & @Mikkelet,
> 
> Thank you all for selecting dart_algolia package for your Dart projects and supporting the development.
> 
> Multiple queries are in our pipeline of our TODOS, we should be rolling-out that functionality by the end of this May.
> 
> Till then you can use an alternative method, I know it's not that efficient as Multiple queries, but just a workaround:
> 
> ```dart
>    AlgoliaQuery queryA = algolia.instance.index('indiceA').search('john');
>    AlgoliaQuery queryB = algolia.instance.index('indiceB').search('john');
> 
>    // Perform multiple facetFilters
>    queryA = queryA.setFacetFilter('status:published');
>    queryA = queryA.setFacetFilter('isDelete:false');
> 
>    // Perform multiple facetFilters
>    queryB = queryB.setFacetFilter('status:published');
>    queryB = queryB.setFacetFilter('isDelete:false');
> 
>    // Get Result
>    List<AlgoliaQuerySnapshot> snap = await Future.wait([queryA.getObjects(), queryB.getObjects()]);
> ```
> 
> 🍻

I get a "The element type 'Future<AlgoliaQuerySnapshot>' can't be assigned to the list type 'Future<AlgoliaObjectSnapshot>'" error! Any ideas? :)

**Comment by nhathiwala** [comment]
Good news! Multi-Query option is now supported. Update the SDK version to `^0.1.6`

We have created a whole new interface just for Multi-Query. You can perform the following action:
1. Add Query ``.addQuery(AlgoilaQuery query)``
2. Add Queries ``.addQueries(List<AlgoilaQuery> queries)``
3. Clear Queries ``.clearQueries()``

  ```dart
    AlgoliaQuery queryA = algolia.instance.index('users').search('john');
    AlgoliaQuery queryB = algolia.instance.index('jobs').search('business');

    // Perform multiple facetFilters
    queryA = queryA.setFacetFilter('status:active');
    queryA = queryA.setFacetFilter('isDelete:false');

    // Perform multiple facetFilters
    queryB = queryB.setFacetFilter('isDelete:false');

    // Get Result/Objects
    List<AlgoliaQuerySnapshot> snap =
        await algolia.multipleQueries.addQueries([queryA, queryB]).getObjects();  
  ```
