### ISSUE TITLE
Algolia search in flutter, index issue.

### ISSUE THREAD

**Issue by parthvora-techypanther** [knoxpo/dart_algolia#17]
I am trying to provide search in flutter app using algolia. But i have different results coming from it.
I search with one keyword in website and in app. In both i get different results. In app using algolia, i have found that 5 results from the top of the list are not getting displayed in my flutter app. 
Amy suggestions you have on how to achieve this? 
I have added hits per page and page for pagination.
If i remove them, then i get the proper results, but i need to add pagination in my app also.

**Comment by mmkumr** [comment]
Can you share the pagination code with me. I am try to implement this in my flutter project.
