### ISSUE TITLE
Runtime exception when using setHitsPerPage in multi query

### ISSUE THREAD

**Issue by tobiwild** [knoxpo/dart_algolia#22]
Dart version: 2.7.0
Flutter version: v1.12.13+hotfix.6

**Describe the bug**
The following code raises a runtime exception:
```dart
    final queries = App.algolia.multipleQueries;
    queries.addQuery(App.algolia.index('my_index').setHitsPerPage(1));
    queries.getObjects();
```
It looks like the URI constructor when building the request payload needs the values of the query parameters to be `String|Iterable<String>` : https://api.dartlang.org/stable/2.7.0/dart-core/Uri/Uri.html
The value of parameter `hitsPerPage` is an int, so the constructor fails.

**Comment by shinriyo** [comment]
setHitsPerPage doesn't work.

**Comment by bdairy** [comment]
Same issue here

**Comment by Abacaxi-Nelson** [comment]
can create a PR, but @krhknoxpo seems not avaialble to accept them..
```dart
 AlgoliaQuery setHitsPerPage(String value) {
    assert(!_parameters.containsKey('hitsPerPage'));
    return _copyWithParameters(<String, dynamic>{'hitsPerPage': value});
  }
````
