### ISSUE TITLE
can't pass List<dynamic> to setFacetFilter

### ISSUE THREAD

**Issue by hiko1129** [knoxpo/dart_algolia#23]
Dart version: 2.7.0
Flutter version: 1.12.13

**Expected behavior**
setFacetFilter can receive `List<dynamic>`

https://github.com/knoxpo/dart_algolia/blob/96dc03d8005e4bcd3dc3ebdea90045adcff18e32/lib/src/query.dart#L254

**Actual behavior**
setFacetFilter can only receive `List<String>` or `String`

https://github.com/knoxpo/dart_algolia/blob/96dc03d8005e4bcd3dc3ebdea90045adcff18e32/lib/src/query.dart#L261

**Comment by wizawuza** [comment]
I'm guessing you've either moved on or fixed this yourself, but I've gotten around this simply by doing something more like this:
```
query = query.setFacetFilter(['category:Book', 'category:Movie']);
query = query.setFacetFilter(['author:John Doe']);
```

**Comment by shinriyo** [comment]
I wanna watch snipet of your json on the your alolia.

**Comment by shinriyo** [comment]
@wizawuza 



does it work?

**Comment by wizawuza** [comment]
> @wizawuza
> 
> does it work?

When you chain setFacetFilter?

Yep it does.
