### ISSUE TITLE
setInsidePolygon method does not support polygons, but triangles only

### ISSUE THREAD

**Issue by Igor3T** [knoxpo/dart_algolia#24]
Dart version: 2.7
Flutter version: >=2.6.0 <3.0.0

Implementation of the setInsidePolygon method does not support polygons, but triangles only:

AlgoliaQuery setInsidePolygon(List<BoundingPolygonBox> value) {
    assert(value != null && value.isNotEmpty, 'value can not be empty');
    assert(!_parameters.containsKey('insidePolygon'));
    List<List<num>> list = value
        .map((v) => [v.p1Lat, v.p1Lng, v.p2Lat, v.p2Lng, v.p3Lat, v.p3Lng])
        .toList();
    return _copyWithParameters(<String, dynamic>{'insidePolygon': list});
  }

According to algolia api documentation, any even number of coordinates should work: 
"To specify multiple polygons, pass an list of lists of floats (each inner array must contain an even number of values, with a minimum of 6)". [https://www.algolia.com/doc/api-reference/api-parameters/insidePolygon/]

Probably, the BoundingPolygonBox class should contain a List of numbers, not just six parametres: num p1Lat;   num p1Lng;  num p2Lat;  num p2Lng;  num p3Lat;  num p3Lng;

**Comment by nhathiwala** [comment]
If you are still facing this issue, you can reopen this issue and see what can be done.
