### ISSUE TITLE
Failed host lookup: 'wzgqmequtp-dsn.algolia.net' (OS Error: nodename nor servname provided, or not known, errno = 8)

### ISSUE THREAD

**Issue by XSiyabonga** [knoxpo/dart_algolia#27]
Dart version: 2.9.0
Flutter version: 1.19.0-4.1.pre

**Describe the bug**
This is caught during setSettings method and persists on iOS with active internet connect.

**To Reproduce**
` try{
AlgoliaSettings settings = await algolia.index('Indice').settings;
}catch(e){
//SocketException: Failed host lookup: 'wzgqmequtp-dsn.algolia.net' (OS Error: nodename nor servname provided, or not known, errno = 8)
}`

**Desktop (please complete the following information):**
 - OS: Mac

**Smartphone (please complete the following information):**
 - Device: iOS Simulator, iOS Device
 - OS: 13.5.1

**Comment by AustrisC** [comment]
Did you manage to resolve this one?
