### ISSUE TITLE
Query getObjects does not Report When an API Key does not have acess to an Index

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [knoxpo/dart_algolia#28]
Dart version: `2.9.0-21.0.dev`
Flutter version: ` 1.21.0-2.0.pre.66`

## Description

I used an API key which apparently was not compatible with the index I was trying to query.  
However, the client only threw the following error: `NoSuchMethodError: invalid member on null: 'map'`

This means that it took a while to figure out that I had to get a new API key for the query.

```dart
client.instance.index('index').search('').getObjects()
```

**Comment by zakton5** [comment]
Same issue. My trial had expired and I was getting this type of error because of it.

**Comment by nhathiwala** [comment]
I can close this issue as this problem has been addressed in full stable version of ‘1.0.0’. 

There is an all new implementation of new error handling interface, I hope this helps you easy debug your errors.

**Comment by creativecreatorormaybenot** [comment]
Hi @nhathiwala :) I checked your null safety version and it is filled with nullable properties. Why is that? I checked the source code and the nullability does not make sense in most cases, i.e. the properties cannot be `null` in any case, though, you have still marked them nullable.

Do you think you can improve on that?

**Comment by nhathiwala** [comment]
Can you create a new issue for the same and also highlight some variable which you are concerned  about

**Comment by creativecreatorormaybenot** [comment]
@nhathiwala it looks like you just fixed it yesterday...

I will let you know if someone is still off after your cleanup.
