### ISSUE TITLE
Get Facets method is already implemented?

### ISSUE THREAD

**Issue by cubissimo** [knoxpo/dart_algolia#3]
First of all THANKS! We are planning to huge use algolia with flutter. Cause of that we will start to colaborate to your repo.

There is a method to query facets already implemented?
https://www.algolia.com/doc/api-reference/api-methods/search-for-facet-values/

Tks

**Comment by nhathiwala** [comment]
@cubissimo you are most welcomed to contribute! 

Faceting (Status: 4/4 | Completed)
- `.setFacets(List<String> value)`
- `.setMaxValuesPerFacet(int value)`
- `.setFacetingAfterDistinct({bool enable = true})`
- `.setSortFacetValuesBy(AlgoliaSortFacetValuesBy value)`

You may start helping out with TODO docs or if you want to work on functionality, then you can refer to `README.md`, we have listed all functionality which are pending.

**Comment by cubissimo** [comment]
Tks for your fast response.

I'm trying to use faceting methods, but when i setFacets i cant find the facet results. What property the facets values will come?

we start to learn about the repo and todos to contribute. :)

**Comment by cubissimo** [comment]
@nhathiwala Now i can report this as a bug.

in `query_snapshot.dart` i cant find `facets`.

adding 
```
dynamic facets;
AlgoliaQuerySnapshot({
    this.facets,
  });
this.facets = map['facets'];
```
If can a leave the `facets` property as `dynamic` i can make a PR of this fix.

**Comment by nhathiwala** [comment]
Yes, you may go ahead with a PR and here is an suggestion to you proposed code.
```dart
// facets response is a `Map` type
Map<String, dynamic> facets;

AlgoliaQuerySnapshot({
    this.facets,
});

// With `null`check
this.facets = map['facets'] != null ?  map['facets'] : {};
```
You may also help me to add documention to this class. Thanks!
