### ISSUE TITLE
[Feature]convert string for debug

### ISSUE THREAD

**Issue by shinriyo** [knoxpo/dart_algolia#30]
**Is your feature request related to a problem? Please describe.**
```
    const algolia = AlgoliaService.algolia;
    final query = algolia.instance.index('hoge');

    final query = _getQuery()
        .setFilters(
          'a=1',
        )
        .setFacetFilter("[["category:Book", "category:Movie"], "author:John Doe"]")
```

later, I want to convert to query string.

```
print(query.queryString());
```

just `query.toString();` is 
I/flutter (12300): Instance of 'AlgoliaQuery'

**Describe the solution you'd like**
print query string.

**Describe alternatives you've considered**
add queryString() feature.

**Additional context**
N/A

**Comment by nhathiwala** [comment]
Nice suggestion, will work on that in next release.

**Comment by nhathiwala** [comment]
Introduced this functionality for all Algolia class you may try `.toString()` after upgrading to version `^1.0.1`
