### ISSUE TITLE
JsonUnsupportedObjectError' is not a subtype of type 'FutureOr<AlgoliaTask>'

### ISSUE THREAD

**Issue by muhammadshahidraficp** [knoxpo/dart_algolia#33]
when trying to update algolia index records, throwing error JsonUnsupportedObjectError' is not a subtype of type 'FutureOr<AlgoliaTask>'

**Comment by nhathiwala** [comment]
Please, can you share code snippet, with your dart version and what exactly are you try to execute.

**Comment by nhathiwala** [comment]
Due to no response this issue is being closed.
