### ISSUE TITLE
Search on two parameters

### ISSUE THREAD

**Issue by rajflutter** [knoxpo/dart_algolia#34]
how to search/match on two search parameters . Searching the review index to match on ProductID and then searchtext on comments

_algoliaApp.instance
        .index("review")
        .search(widget.productID)
        .search(widget.searchText)

**Comment by nhathiwala** [comment]
It is now possible, try 'similarQuery'

```dart
_algoliaApp.instance
.index("review")
.query(widget.productID)
.similarQuery(widget.searchText)
```
