### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by Yegorisa** [knoxpo/dart_algolia#35]
Since Null Safety is in beta, it is time to update Dart Algolia library to support null safety. Are there any timelines on this? Thanks!

**Comment by IchordeDionysos** [comment]
@nhathiwala You should be unblocked to migrate to null safety all packages `package:algolia` depends on are migrated to null safety.

This is a request to add support for [null safety](https://dart.dev/null-safety) to `package:algolia`.
We depend on your awesome package, so would be great to have null safety enabled.

The Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

**Comment by IchordeDionysos** [comment]
The new Dart version was just released 😍 
https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87

**Comment by behnamsattar** [comment]
Null safety is out. Please update this package ASAP.

**Comment by saurabhguptarock** [comment]
> Null safety is out. Please update this package ASAP.

The developer has not committed any code for 2 years. I doubt that.
But I also use algolia in my app, so what should I do.

**Comment by Yegorisa** [comment]
@saurabhguptarock the only option now is to Fork and migrate it yourself

**Comment by saurabhguptarock** [comment]
> @saurabhguptarock the only option now is to Fork and migrate it yourself

can you fork and release a new package. I don't know how to do it. Please it would be a great help

**Comment by disparta** [comment]
@saurabhguptarock I'm forking it now. I will keep you posted.

**Comment by disparta** [comment]
@saurabhguptarock  Please check this out and let me know if there are any issues.

https://pub.dev/packages/algolia_ns/

**Comment by saurabhguptarock** [comment]
> @saurabhguptarock Please check this out and let me know if there are any issues.
> 
> https://pub.dev/packages/algolia_ns/

Thank you so much. The help means a lot to me 🙂

**Comment by nhathiwala** [comment]
@saurabhguptarock @disparta @Yegorisa @IchordeDionysos  announcement to all, we have couple of new features for Algolia library along with null-safety implementation to be release. You may see a whole new update by this 6th March, 2021. Apologies, to all who are facing issue.

We are also looking for collaboration opportunities for new contributors to join this projects. Email me with your interest to join as collaboration: nhathiwala {at} knoxpo.com

**Comment by nhathiwala** [comment]
I can close this issue as this problem has been addressed in full stable version of ‘1.0.0’. 

There is an all new implementation of new error handling interface, I hope this helps you easy debug your errors.
