### ISSUE TITLE
Support for optional Words

### ISSUE THREAD

**Issue by enex** [knoxpo/dart_algolia#37]
**Describe the solution you'd like**
It would be nice to extends AlgoliaQuery to also contain optionalWords.

https://www.algolia.com/doc/api-reference/api-parameters/optionalWords/

**Comment by nhathiwala** [comment]
I can close this issue as this problem has been addressed in full stable version of ‘1.0.0’. 

There is an all new implementation of new error handling interface, I hope this helps you easy debug your errors.
