### ISSUE TITLE
Algolia setFacetFilter array

### ISSUE THREAD

**Issue by Maliffic** [knoxpo/dart_algolia#4]
I noticed with this package that when setting a facet filter you can pass in strings which when it posts to Algolia it makes it an AND call on the index. 

If you want to query OR the format is this: 

 "facetFilters": [
  [
   "location:Cape Town",
   "location:Durban"
  ]
 ]

but if you pass the array as a string it doesn't format correctly and it retrieves 0 hits:

"facetFilters": [
    "[location: Bloemfontein, location: Cape Town]"
  ],

**Comment by nhathiwala** [comment]
Hi @Maliffic please try the latest version of the library. As per your feedback, I have implemented a solution where you can FaceFilter with String or List<String> values.  Thank you for bringing this enhancement to my notice.
