### ISSUE TITLE
Empty search queries should be allowed

### ISSUE THREAD

**Issue by zaidkazi** [knoxpo/dart_algolia#40]
In `query.dart` it is specified that 

"`If the text is empty or absent, the search will match every object in your index.`"

Further the library prevents an empty query string. This directly falls against Algolia's pinned suggestion returns which allows you to pin items to return when an empty search is provided.

I don't believe restricting the query to non empty string is the right functionality.

**Comment by nhathiwala** [comment]
Resolved this bug in version `1.0.1`
