### ISSUE TITLE
deleteObject() fails with: "Path not supported by Algolia REST API."

### ISSUE THREAD

**Issue by jimmyff** [knoxpo/dart_algolia#47]
[object([String? path])](https://github.com/knoxpo/dart_algolia/blob/master/lib/src/index_reference.dart#L33) accepts a parameter `path` which I thought was unusual as I hadn't heard that term, then when I use it and then use [deleteObject()](https://github.com/knoxpo/dart_algolia/blob/master/lib/src/object_reference.dart#L143) I get the mentioned error.

```dart
await algolia
   .index('foobar')
   .object(objectId)
   .deleteObject();
```
fails with:
```
{message: Path not supported by Algolia REST API. Please have a look at http://www.algolia.com/doc/rest_api for the list of valid commands, status: 404}
```
Aloglia docs for deleteObject:
https://www.algolia.com/doc/rest-api/search/#delete-object

**Comment by kenshi-web** [comment]
> [object([String? path])](https://github.com/knoxpo/dart_algolia/blob/master/lib/src/index_reference.dart#L33) accepts a parameter `path` which I thought was unusual as I hadn't heard that term, then when I use it and then use [deleteObject()](https://github.com/knoxpo/dart_algolia/blob/master/lib/src/object_reference.dart#L143) I get the mentioned error.
> 
> ```dart
> await algolia
>    .index('foobar')
>    .object(objectId)
>    .deleteObject();
> ```
> 
> fails with:
> 
> ```
> {message: Path not supported by Algolia REST API. Please have a look at http://www.algolia.com/doc/rest_api for the list of valid commands, status: 404}
> ```
> 
> Aloglia docs for deleteObject: https://www.algolia.com/doc/rest-api/search/#delete-object

Try below
`await algolia.index('foobar').object(objectId).ref.deleteObjects()`

just getting the object only return a snapshot, you need the reference to perform deletion.

**Comment by nhathiwala** [comment]
Deleting objects have been working fine without any issues. I'm sure how you are getting issue. Is your `objectId` is defined?

**Comment by nhathiwala** [comment]
@jimmyff Due to no response form you I'm closing this issue for now.
