### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED: application verification failure on iOS simulator

### ISSUE THREAD

**Issue by zakton5** [knoxpo/dart_algolia#48]
Dart version: [eg: 2.12.0]
Flutter version: [eg: 2.0.0 (stable)]

**Describe the bug**
Starting with v1, I get the error in the title when using an iOS simulator. Physical iOS devices work fine.

**To Reproduce**

1. Attempt to use `.query` in a flutter app running on an iOS simulator

**Expected behavior**
I expect there to be no error and my `.query` call to return results

**Screenshots**

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone 12 Pro Max]
- OS: [e.g. iOS14.3]

**Comment by nhathiwala** [comment]
Error seem to be not related to this library.
