### ISSUE TITLE
How to get `_rankingInfo`?

### ISSUE THREAD

**Issue by cubissimo** [knoxpo/dart_algolia#5]
There is a way to access `_rankingInfo` result object?

doc ref:

https://www.algolia.com/doc/guides/managing-results/refine-results/geolocation/how-to/geo-ranking-info/

**Comment by nhathiwala** [comment]
Hi @cubissimo  please try the latest version of the library. As per your reporting, I have implemented a solution where you can get  `_rankingInfo `.  

However, this is one the Advance query parameter for which I had not yet started my work on it. But as per your request, I have managed to come up with the functionality.

If you are interested, you can contribute to this library and help me complete the pending task list.
