### ISSUE TITLE
setData() fails with Path not supported by Algolia REST API

### ISSUE THREAD

**Issue by louisdeveseleer** [knoxpo/dart_algolia#52]
Dart version: 2.12.3
Flutter version: 2.0.6 (stable)

setData() fails and gives the error message : "Path not supported by Algolia REST API. Please have a look at http://www.algolia.com/doc/rest_api for the list of valid commands, status: 404"

`
  Future<void> updateName(String id, String name) async {
    var index = algoliaUserNames.instance.index('UserNames');
    try {
      await index.object(id).setData({'name': name});
    } catch (e) {
      print(e.error);
    }
  }
`
If replacing setData() by updateData() on an existing object, it works fine.
setData fails whether the object exists or not.
I tried with a custom API key where the "addObject" ACL had been added, and I also tried with the Admin API key, without success.

Try using setData().

**Comment by nhathiwala** [comment]
Resolved in version `^1.0.4`
