### ISSUE TITLE
Add feature for analytics (search-insights Library)

### ISSUE THREAD

**Issue by saurabhguptarock** [knoxpo/dart_algolia#53]
As the official documentation says to include search-insights library for JS, IOS, and Android

![image](https://user-images.githubusercontent.com/32234038/117919018-e3089480-b309-11eb-8b52-36511776c93b.png)

**Comment by cybertheory** [comment]
This Issue has a PR pending!
[#56](https://github.com/knoxpo/dart_algolia/pull/56)

**Comment by nhathiwala** [comment]
As @creativecreatorormaybenot mentioned, it's been already included. Initital implemention by [@algirdasmac](https://github.com/algirdasmac) committed on 15 Jun [PR](https://github.com/knoxpo/dart_algolia/pull/56/commits/8dc068ed16f7cf0c6747ec28d0e17fcf7b433f7f) author status is also included on the file.
