### ISSUE TITLE
OR method in facetFilter() method

### ISSUE THREAD

**Issue by sithu-aung** [knoxpo/dart_algolia#54]
Dear All , 
I would like to ask to guide me how to use OR disclosure in facetFilter().

**Comment by kenshi-web** [comment]
`facetFilter(['category:A', 'category:B'])`

Equal to category = A OR category = B
use square brackets to indicate OR

> Dear All ,
> I would like to ask to guide me how to use OR disclosure in facetFilter().

**Comment by nhathiwala** [comment]
@kenshi-web You may just check the official documentation, pretty self-explanatory https://www.algolia.com/doc/api-reference/api-parameters/facetFilters/#simple-or-filter
