### ISSUE TITLE
Algolia compatibility issue with firebase ^5.0.2

### ISSUE THREAD

**Issue by anelecat** [knoxpo/dart_algolia#6]
I am trying to use algolia dart package to my angular dart application and I have encountering compatibility issues with firebase ^5.0.2 because it uses/depends on http ^0.11.3 and algolia depends on http ^0.12.0. 

Can algolia be forced or modified to also use http ^0.11.3 to http ^0.12.0.

**Comment by nhathiwala** [comment]
Hi @anelecat, this isn't an issue from this library. Firebase is currently depended on an older version of `http` library. However, I can suggest you a way to get a work around this bug:

Fork this library, and make the necessary changes in your side of a copy and then just use your forked repo as your git base library in `pubspec.yaml`.

I hope this helps out bro 🍻
