### ISSUE TITLE
Error in AlgoliaQuerySnapshot

### ISSUE THREAD

**Issue by Rart3001** [knoxpo/dart_algolia#60]
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (2 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
algolia: ^1.0.1

**Describe the bug**
AlgoliaQuerySnapshot throw exception "I/flutter (13087): type 'Null' is not a subtype of type 'int'" 

**To Reproduce**
Make a query and call getObejects() method these are my parameters used:

![image](https://user-images.githubusercontent.com/12099493/126043092-04af8ce7-d713-4b02-ad03-e2a0e633ec69.png)

The problem is when used:

```
AlgoliaQuery query =
        algolia.instance.index(index!).setOffset(from).setLength(size);
```

If you use setPage() work ok.

**Expected behavior**
Return the Algolia result

**Screenshots**
![image](https://user-images.githubusercontent.com/12099493/126042940-5e5d3ff2-7851-4b6c-b071-daf512a04d0a.png)

![image](https://user-images.githubusercontent.com/12099493/126042953-74a9738a-4982-419d-89b5-8e78ae500f31.png)

The map object don't have all key values

**Additional context**
After update to null safety the exception thrown.

**Comment by Rart3001** [comment]
Hi, So my PR was not merge?

**Comment by Rart3001** [comment]
> This was integrated into `master` in [9e60161](https://github.com/knoxpo/dart_algolia/commit/9e60161ac9db790b9cf84be276649d1ce9344454).
> 
> The maintainer is not properly attributing PRs / addressing issues and instead just takes code from PRs and integrates it into `master` without notice. I just wanted to let you know that this issue has been fixed.

Hi, So my PR was not merge?

**Comment by nhathiwala** [comment]
@Rart3001 If you see in newer implementation of `AlgoliaQuerySnapshot`, I removed many of the possible nullable variables from constructor and moved it to getter variables. Your PR was not merged due to this reason. @creativecreatorormaybenot please review it.
