### ISSUE TITLE
Searching in facet values

### ISSUE THREAD

**Issue by alkaitagi** [knoxpo/dart_algolia#64]
**Is your feature request related to a problem? Please describe.**
It seems like the [searchForFaceValues](https://www.algolia.com/doc/guides/managing-results/refine-results/faceting/#searching-in-facet-values) method is not supported. Having this is very important for me as I need to implement tags autocompletion.

**Describe the solution you'd like**
Right now the `query` method performs the search only over the record objects. Perhaps another method is needed, something like `queryFacets` that would allow for the facet filtering.

**Describe alternatives you've considered**
I've tried using `setFacets` method, but it retrieves all the values, which will be thousands. I only need a few tags that start with a text I want to perform a search with.

**Comment by alkaitagi** [comment]
Great to hear. I will test within a week and then update the issue accordingly.

**Comment by alkaitagi** [comment]
@creativecreatorormaybenot finally got to test the feature:
```
 _index.facetQuery(
          'tags',
          facetQuery: 'n',
        )
        .then((v) => print('TAG $v'));
```
And run into the error:
```
D/FirebaseAuth(17228): Notifying id token listeners about user ( Nd95yzHl7eYYj6hkqK38q65sTD32 ).
E/flutter (17228): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: Cannot set the body fields of a Request with content-type "application/json".
E/flutter (17228): #0      Request.bodyFields=
package:http/src/request.dart:133
E/flutter (17228): #1      BaseClient._sendUnstreamed
package:http/src/base_client.dart:87
E/flutter (17228): #2      BaseClient.post
package:http/src/base_client.dart:32
E/flutter (17228): #3      post.<anonymous closure>
package:http/http.dart:69
E/flutter (17228): #4      _withClient
package:http/http.dart:164
E/flutter (17228): #5      post
package:http/http.dart:68
E/flutter (17228): #6      AlgoliaIndexReference.facetQuery
package:algolia/src/index_reference.dart:81

```

**Comment by alkaitagi** [comment]
Even ` _index.facetQuery('tags').then((v) => print('TAG $v'));` gives the same error. And yes, I've set `searchable(tags)`.

**Comment by alkaitagi** [comment]
In this package it fails at 
```
 var url =
        '${algolia._host}indexes/$encodedIndex/facets/${Uri.encodeFull(facetName)}/query';
    var response = await http.post(
      Uri.parse(url),
      headers: algolia._headers,
      body: {
        'params': params,
        'facetQuery': facetQuery,
        'maxFacetHits': maxFacetHits,
      },
    );
```
Meaning that the request doesn't even leave the client.

**Comment by creativecreatorormaybenot** [comment]
@alkaitagi nice that you got to test it. I did not implement it, so I cannot help you there. But you should be able to file a new issue / create a PR and with a lot of luck, @nhathiwala will take a look at it.

**Comment by alkaitagi** [comment]
@creativecreatorormaybenot  For me, implementation of this feature is no longer a high priority in my project, so I move on for a while. I close the issue as technically it is implemented, and the new one, as you've said, would be a bug one. When I come at this feature again, if not fixed by then, I will open a new issue and will help to resolve it. For now, thank you for your work!
