### ISSUE TITLE
LateError (LateInitializationError: Field 'addedObject' has not been initialized.)

### ISSUE THREAD

**Issue by NIkos77-cloud** [knoxpo/dart_algolia#68]
Algolia algolia = Application.algolia;
  AlgoliaAPI algoliaAPI = AlgoliaAPI(); 

    await algolia.instance
        .index('product_store_live_HK_price_asc').
        getObjects().then((value) {
          print(value.hits);
        });

**Comment by nhathiwala** [comment]
@NIkos77-cloud  Please can you elaborate your action that you are trying to achieve. BTW class `AlgoliaAPI` is not part of this package.

**Comment by nhathiwala** [comment]
I'm going to close this issue for now. If you face any similar issue again, then you can reopen this issue or can create a new one.
