### ISSUE TITLE
Filters are not being added to query

### ISSUE THREAD

**Issue by timtraversy** [knoxpo/dart_algolia#7]
Dart version: 2.2.0
dart_algolia version: 0.1.4+3

**Describe the bug**
Filters are not being added to query.

**To Reproduce**
```
final AlgoliaQuery _algQuery = algolia.instance.index('index');
_algQuery.setFacetFilter('test:10732');
print(_algQuery.parameters);
// this prints {facetFilters: [], optionalFilters: [], numericFilters: [], tagFilters: []}
```

Running this as as a command line app at the moment. Am I not using `setFacetFilter` correctly?

**Comment by nhathiwala** [comment]
Hi @timtraversy,

I guess this isn't a bug, it's because you are query it all wrong.

If you have worked with any Firestore library, the query method is similar to it. 

 ```dart
AlgoliaQuery _query = algolia.instance.index('contacts').search('john');

// Perform multiple facetFilters
_query = _query.setFacetFilter('status:published');
_query = _query.setFacetFilter('isDelete:false');
print(_query.parameters);
// this prints {facetFilters: [status:published, isDelete:false], optionalFilters: [], numericFilters: [], tagFilters: [], query: john}
```

Everytime you modify your query, you got to save that instance to a working variable. This is due to Algolia for Dart allows user to run multiple queries in their dedicated instances, thus no response 
corruption or overriding.

**Comment by timtraversy** [comment]
Ah ok thanks!

**Comment by nhathiwala** [comment]
You can also do a query like this:
```dart
AlgoliaQuery _query = algolia.instance.index('contacts');

// Perform multiple facetFilters
_query = _query.setFacetFilter('status:published').setFacetFilter('isDelete:false');

// Perform search
_query = _query.search('john');

print(_query.parameters);

// this prints {facetFilters: [status:published, isDelete:false], optionalFilters: [], numericFilters: [], tagFilters: [], query: john}
```

You can mould your query as you like.

**Comment by timtraversy** [comment]
Is there a way to perform multiple queries? Like https://www.algolia.com/doc/api-reference/api-methods/multiple-queries/
