### ISSUE TITLE
Space in facet value breaks request

### ISSUE THREAD

**Issue by dunatron** [knoxpo/dart_algolia#71]
Hey when there is a space in a facet value the network request fails

```
algolia.instance
        .index('NewsAndEventsIndex')
        .setHitsPerPage(HITS_PER_PAGE)
        .query(query)
        .filters('Type:Important dates');
```

on the request is 
```json
{"facetFilters":[],
"optionalFilters":[],
"numericFilters":[],
"tagFilters":[],
"hitsPerPage":10,
"query":"",
"filters":"Type: Important dates"}
```
this is the response
```
{
  "message": "filters: Unexpected token string(dates) expected end of filter at col 15",
  "status": 400
}
```

**Comment by nhathiwala** [comment]
@dunatron  Please can you elaborate your action that you are trying to achieve. I don't see any date in your query.

**Comment by nhathiwala** [comment]
@dunatron  Due too no response for a week, I'm closing this issue for now. Assuming that issue was resolved at your end. However, if you still face the similar issue, you can reopen this issue or create a new.

**Comment by dunatron** [comment]
@nhathiwala sorry for the late response. the issue is on the .filters('Type: some   value') and it would break if there was a space in the value
