### ISSUE TITLE
Can't get queryID

### ISSUE THREAD

**Issue by MonsieurZbanowanYY** [knoxpo/dart_algolia#72]
Flutter version: 2.5.3 (stable)

When I'm trying to get a queryId from QuerySnapshot I'm getting this error:

Error: [+5335 ms] flutter: type 'Null' is not a subtype of type 'String'

`  Future<List<AlgoliaObjectSnapshot>> _operation(String input) async {
    AlgoliaQuery query = algolia.instance.index("job").query(input);
    AlgoliaQuerySnapshot querySnap = await query.getObjects();
    List<AlgoliaObjectSnapshot> results = querySnap.hits;
    try {
      print(querySnap.queryId);
    } catch (ex) {
      print(ex);
    }
    return results;
  }`
<img width="586" alt="Zrzut ekranu 2021-11-11 o 17 31 38" src="https://user-images.githubusercontent.com/81767518/141334350-5b93a5fe-7a35-43b7-b4c4-cef5d280fb8d.png">

**Comment by nhathiwala** [comment]
@MonsieurZbanowanYY we are rolling out a nullable check for that value in `v1.0.3`.
