### ISSUE TITLE
Hits per page not working (throwing error) for multiple queries

### ISSUE THREAD

**Issue by slorop41314** [knoxpo/dart_algolia#76]
Dart version: [eg: 2.12.0]
Flutter version: [eg: 2.0.0 (stable)]

**Describe the bug**
Hits per page for multiple queries is not working. 
Getting type 'int' is not a subtype of type 'Iterable<dynamic>' error instead.

Its working fine for single queries.

**To Reproduce**
For reproduce purpose, can use one query.
1. Create query. 

      AlgoliaQuery firstQuery = algolia.instance
          .index('someIndex')
          .setHitsPerPage(5)
          .query(search);
2.  Call get objects

      List<AlgoliaQuerySnapshot> snap = await algolia.multipleQueries
          .addQueries([firstQuery]).getObjects();
          
          
**Expected behavior**
Should be works fine like single query

**Comment by slorop41314** [comment]
Seems like its due to dart URI queryParameters that only accept String or Iterable String

https://github.com/jonataslaw/getx/issues/857#issuecomment-742043591

**Comment by slorop41314** [comment]
I raised a PR for this fix, kindly check it, thanks.

https://github.com/knoxpo/dart_algolia/pull/77

**Comment by nhathiwala** [comment]
@slorop41314  PR has a fix, it has been merged.
