### ISSUE TITLE
Function _apiCall return JsonMap instead of Response

### ISSUE THREAD

**Issue by imadghiyati** [knoxpo/dart_algolia#79]
Dart version: [eg: 2.12.0]
Flutter version: [eg: 2.0.0 (stable)]

**Describe the bug**

**To Reproduce**

1. Run "getObjects()" in query.dart
2. Debug return of function _apiCall 
3. it returns _JsonMap in the first retry and then "http.Response" in the second retry. 

**Expected behavior**
Get only "http.Response" not _JsonMap

**Screenshots**
After analysis, I found the bug, here is screenshot for the small change to do and to redeliver :) 

![image](https://user-images.githubusercontent.com/8405410/147374451-11bf9c27-632e-4d49-994f-43829e9532ff.png)

**Navigator Chrome :  
I'm using flutter web, the issue is not a blocker in debug mode but after release the app crash

**Additional context**
Please replace the json.decode(reponse.body) by return response only and it will resolve the problem. 

Thank you in advance, 
imad

**Comment by jaxnz** [comment]
Having this issue too

**Comment by zibizz1** [comment]
me too

**Comment by nhathiwala** [comment]
@aemelyanovff PR has a fix, it has been merged.
