### ISSUE TITLE
Bring back fromMap method in AlgoliaObjectSnapshot 

### ISSUE THREAD

**Issue by paulperez-dev** [knoxpo/dart_algolia#81]
I want you to bring back the method `.fromMap` in the object `AlgoliaObjectSnapshot ` that was deleted

**Is your feature request related to a problem? Please describe.**
The method `.fromMap` in the object `AlgoliaObjectSnapshot` was deleted

**Describe the solution you'd like**
Be able to create an `AlgoliaObjectSnapshot` from a map like before.

**Additional context**
This method was available in version 0.1.7 (the one I was using before upgrading to 1.0.0+)

**Comment by nhathiwala** [comment]
May know why would you like to have `AlgoliaObjectSnapshot.fromMap` back?

**Comment by paulperez-dev** [comment]
The idea was to be able to create results manually, but I no longer need this feature. I will close this request.

**Comment by Josefpa** [comment]
Yes Please! Not sure why it would be removed in thefirst place, to do a Mutli Index Search I need to do it with an API then I have to way to convert it back to a Native AlgoliaObjectSnapshot  type
