### ISSUE TITLE
[Production Bug] Algolia search does not work on production environment

### ISSUE THREAD

**Issue by IoanSolovastru** [knoxpo/dart_algolia#85]
I cannot show a list retrieved by Algolia when I am using --release mode in Flutter. It's very interesting that It works just fine when running the app in Flutter Web Debug.
Can anyone help me out with this issue?

Works with:
- [✓] Flutter Web Debug
- [✓] Postman

Error I got in Web Console:
`js_helper.dart:1137 Uncaught TypeError: Cannot read properties of undefined (reading 'h')
    at Object.bf4 (VM939 main.dart.js:27309:16)
    at VM939 main.dart.js:52638:25
    at b_W.a (VM939 main.dart.js:5429:62)
    at b_W.$2 (VM939 main.dart.js:46761:14)
    at aZB.$1 (VM939 main.dart.js:46755:21)
    at abu.oj (VM939 main.dart.js:47823:32)
    at aQY.$0 (VM939 main.dart.js:47180:11)
    at Object.EG (VM939 main.dart.js:5562:40)
    at av.u7 (VM939 main.dart.js:47112:3)
    at a64.dj (VM939 main.dart.js:46750:8)`

Flutter  doctor:
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-x64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
[✓] VS Code (version 1.64.0)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

Snipped code:
Algolia call function:
`  Future<AlgoliaQuerySnapshot> getEmployee(String name) async {
    AlgoliaQuery query = algolia.instance
        .index(employeeIndexName)
        .facetFilter('companyId:${userController.user.companyId}')
        .query(name);
    AlgoliaQuerySnapshot snap = await query.getObjects();
    return snap;
  }`

Reveal in list:
`FutureBuilder(
              future: AlgoliaService().getEmployee(searchQuery),
              builder: (BuildContext context,
                  AsyncSnapshot<AlgoliaQuerySnapshot> snapshot) {
                if (snapshot.hasError) {
                  return Text('Something went wrong');
                }

                if (snapshot.connectionState == ConnectionState.waiting) {
                  return Center(
                    child: CircularProgressIndicator(),
                  );
                }
               return Text("No errors");
             )
`

**Comment by lucaphen** [comment]
Facing an identical issue. Is there any update on whether it will be fixed?

**Comment by khotenko** [comment]
Have the same issue. 

It seems release/production deployment to web when using Flutter 2.10.1 and algolia: ^1.0.4 this line:

`AlgoliaQuerySnapshot snap = await query.getObjects();`

throws error

NoSuchMethodError: method not found: 'h' on null

The snapshot stackTrace is:

```
Error: TypeError: Cannot read properties of undefined (reading 'h')
at Object.awd (https://mysite.firebaseapp.com/main.dart.js:21594:16)
at https://mysite.firebaseapp.com/main.dart.js:40326:21
at aln.a (https://mysite.firebaseapp.com/main.dart.js:5325:62)
at aln.$2 (https://mysite.firebaseapp.com/main.dart.js:35114:14)
at akq.$1 (https://mysite.firebaseapp.com/main.dart.js:35108:21)
at SE.mx (https://mysite.firebaseapp.com/main.dart.js:35962:32)
at afi.$0 (https://mysite.firebaseapp.com/main.dart.js:35448:11)
at Object.v_ (https://mysite.firebaseapp.com/main.dart.js:5416:40)
at aa.pm (https://mysite.firebaseapp.com/main.dart.js:35377:3)
at OD.cX (https://mysite.firebaseapp.com/main.dart.js:35101:8)
```

It is quite odd because it seems to be working perfectly fine in debug mode.

**Comment by rodrigoaguilar** [comment]
Same here

**Comment by eyals** [comment]
+1

**Comment by dreamsandcode** [comment]
Also experiencing this same issue :(

**Comment by mario202k** [comment]
Same here
https://stackoverflow.com/questions/71005507/dart-nosuchmethoderror-method-not-found-h-on-null/71006211

**Comment by cantuccis** [comment]
+1

**Comment by IoanSolovastru** [comment]
As a temporary fix, try changing the dependency to: 1.0.2
`dependencies:
    algolia: '1.0.2'`

This worked for me.

**Comment by alexobviously** [comment]
Yeah I've also got this bug

**Comment by jtmuller5** [comment]
There is a PR with the fix but it hasn't been merged yet. If you want to pull directly from that repo, add this to your pubspec.yaml:

```
algolia:
    git: https://github.com/aemelyanovff/dart_algolia
```

**Comment by nhathiwala** [comment]
@aemelyanovff PR has a fix, it has been merged.
