### ISSUE TITLE
`AlgoliaIndexReference.facetQuery` should accept facets without `objectID`

### ISSUE THREAD

**Issue by Chralu** [knoxpo/dart_algolia#88]
Flutter version: 2.10.3 (stable)

**Describe the bug**
When querying a simple `string` facet, library throws a `"type 'Null' is not a subtype of type 'String'"` error.

**To Reproduce**

1. In Algolia settings, setup a facet on a `string` property
2. In your Flutter code, run a query like : 

```dart
final algolia = Algolia.init(
      applicationId: <my_application_id>,
      apiKey: <my_api_key>,
);

await algolia
        ?.index(<my_index>)
        .facetQuery(<my_simple_facet_name>);
```

It will throw an error when converting Algolia response to `AlgoliaFacetValueSnapshot`.

**Expected behavior**
`AlgoliaFacetValueSnapshot.objectID` should accept `null` value.

**Comment by nhathiwala** [comment]
This has been fix in `1.0.5`
