### ISSUE TITLE
filter or facetFilter not working for algolia search from flutter

### ISSUE THREAD

**Issue by PavanKaranji** [knoxpo/dart_algolia#92]
Dart version: [eg: 2.12.0]
Flutter version: [eg: 2.0.0 (stable)]

**Describe the bug**
I was following your document as it is and created a algolia index for book and try to search on author and title and their is a query level filter where he should belong to that book community so tried to pass coummunityId for filter and also tried with facetFilter but nothing is returning.

Code:
AlgoliaQuery algoliaQuery =
        algolia.instance.index("book_search").query(input);
  algoliaQuery = algoliaQuery.facetFilter('communityId:Dhatu');

**Comment by nhathiwala** [comment]
Try `algoliaQuery.getObjects()`

**Comment by nhathiwala** [comment]
@PavanKaranji due to no response from you, I'm closing this issue.

**Comment by rlee1990** [comment]
@nhathiwala i can state I have the same issue even after adding  ```algoliaQuery.getObjects()```

**Comment by CodeWithKamal** [comment]
@nhathiwala still same issue. please fix

**Comment by wiztensai** [comment]
me too, still same issue.
