### ISSUE TITLE
Unsupported operation: Platform.operatingSystem

### ISSUE THREAD

**Issue by prologikus** [knoxpo/dart_algolia#94]
in file lib/src/algolia.dart
line 60, 61
Platform.operatingSystem
Platform.version

throwing exception on Flutter web, it's a known flutter issue, please replace them with something else :(

https://github.com/flutter/flutter/issues/36126

**Comment by nhathiwala** [comment]
This issue has been fixed in version `v1.1.1`, please upgrade the package.
